[package]
name = "tutto_sim"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.81"
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
ron = "0.8.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.58"
