[package]
name = "tutto_sim"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.81"
arrayvec = "0.7.4"
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"
serde = { version = "1.0.197", features = [ "derive" ] }
serde_json = "1.0.115"
thiserror = "1.0.58"
